# This file tells Railway how to build and deploy your services.

[build]
# This is the most important line: it forces Railway to use the
# Nixpacks builder, which has Node.js and npm installed.
builder = "nixpacks"

[deploy]
# The command to start the server after it's built.
startCommand = "npm start"
# Tell Railway how to check if the server is healthy.
healthcheckPath = "/"
healthcheckTimeout = 120